spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_management
    username: postgres
    password: 10isIlleg@l

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always

info:
  app:
    name: Spring Webservices
    description: Spring Boot Restful Webservices Demo
    version: 1.0.0
