spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_management
    username: postgres
    password: 10isIlleg@l

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
